spring:
  jpa.hibernate.ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/chat_room
    username: chat_room
    password: chat_room
    driver-class-name: com.mysql.cj.jdbc.Driver

chat-room-service:
  ui-url: http://localhost:4200