version: '3.6'

services:
  mysql:
    image: mysql
    container_name: mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"